apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yas
  namespace: argocd
spec:
  description: YAS dev/staging GitOps project

  sourceRepos:
    - https://github.com/TrNhDuong/yas_devops.git
    - https://stakater.github.io/stakater-charts

  destinations:
    - server: https://kubernetes.default.svc
      namespace: yas-dev
    - server: https://kubernetes.default.svc
      namespace: yas-staging

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"