apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
      listen 80;

      location ~ ^/api/product/?(.*)$ {
        rewrite ^/api/product/?(.*)$ /$1 break;
        proxy_pass http://product;
      }

      location ~ ^/api/cart/?(.*)$ {
        rewrite ^/api/cart/?(.*)$ /$1 break;
        proxy_pass http://cart;
      }

      location ~ ^/api/customer/?(.*)$ {
        rewrite ^/api/customer/?(.*)$ /$1 break;
        proxy_pass http://customer;
      }

      location ~ ^/api/inventory/?(.*)$ {
        rewrite ^/api/inventory/?(.*)$ /$1 break;
        proxy_pass http://inventory;
      }

      location ~ ^/api/media/?(.*)$ {
        rewrite ^/api/media/?(.*)$ /$1 break;
        proxy_pass http://media;
      }

      location ~ ^/api/order/?(.*)$ {
        rewrite ^/api/order/?(.*)$ /$1 break;
        proxy_pass http://order;
      }

      location ~ ^/api/tax/?(.*)$ {
        rewrite ^/api/tax/?(.*)$ /$1 break;
        proxy_pass http://tax;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: internal-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80