name: Gitleaks Security Scanon:  
on: 
  push:    
    branches: [ "**" ]  
  pull_request:   
    branches: [ "**" ]  
  schedule:    
    - cron: "0 0 * * *"  
  workflow_dispatch:
  
jobs:  
  scan:    
    name: Gitleaks Scan    
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout Source Code        
        uses: actions/checkout@v4       
        with:          
          fetch-depth: 0      
          
      - name: Run Gitleaks Official Action        
        uses: gitleaks/gitleaks-action@v2        
        env:          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:          
          config-path: gitleaks.toml